.catalog:
  name: "per-host-subnet"
  version: "v0.0.1"
  minimum_rancher_version: v1.6.3-rc1
  questions:
    - variable: "RANCHER_BRIDGE"
      label: "Bridge"
      description: "Name of bridge to use."
      type: "string"
      default: "rph0"
      required: true
    - variable: "RANCHER_DEBUG"
      label: "Enable Debug Logs"
      description: "This will enable very verbose debug logs."
      type: "boolean"
      default: "false"
      required: true
    - variable: MTU
      label: "MTU for the network"
      description: "Adjust the MTU for the network"
      required: true
      default: 1500
      type: int
    - variable: "RANCHER_HAIRPIN_MODE"
      label: "Enable Hairpin mode"
      description: "If this is enabled, Promiscuous mode needs to be disabled."
      type: "boolean"
      default: "false"
      required: true
    - variable: "RANCHER_PROMISCUOUS_MODE"
      label: "Enable Promiscuous mode on the bridge"
      description: "If this is enabled, Hairpin mode needs to be disabled."
      type: "boolean"
      default: "true"
      required: true
    - variable: "HOST_NAT"
      label: "Enable Host NAT"
      description: "Flag to enable/disable NAT for subnet"
      type: "boolean"
      default: "true"
      required: true
